import { FeaturedPosts } from "@/components/FeaturedPosts"
import { Hero } from "@/components/Hero"
import { PostItem } from "@/components/Posts/post"
import Head from 'next/head'

const posts: PostItem[] | [] = [ {
  id: 'p1',
  title: 'Getting started with NextJS',
  excerpt: 'NextJS is the React framework for production - it makes building fullstack React apps and sites a breeze and ships with built-in SSR.',
  slug: 'getting-started-with-nextjs',
  image: 'nextjs.png',
  content: 'NextJS is the React framework for production - it makes building fullstack React apps and sites a breeze and ships with built-in SSR.',
  date: '2021-05-10'
},
{
  id: 'p2',
  title: 'Getting started with NestJS 2',
  excerpt: 'NestJS 2 is a progressive Node.js framework for building efficient, reliable and scalable server-side applications.',
  slug: 'getting-started-with-nestjs-2',
  image: 'nestjs.png',
  content: 'NestJS 2 is a progressive Node.js framework for building efficient, reliable and scalable server-side applications.',
  date: '2021-05-11'
}]

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Hero />
        <FeaturedPosts posts={posts} />
      </>
    </>
  )
}
