import "@/app/globals.css";
import Header from "@/components/header";
import { Container, CssBaseline } from "@mui/material";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import authenticated from "./auth/authenticated";
import Providers from "./providers";

const inter = Inter( { subsets: [ "latin" ] } );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {

  const isAuthenticated = await authenticated();

  return (
    <html lang="en" suppressHydrationWarning={true} data-qb-installed={true}>
      <body className={inter.className}>
        <Providers authenticated={isAuthenticated}>
          <CssBaseline />
          <Header />
          <Container>{children}</Container>
        </Providers>
      </body>
    </html>
  );
}