import { PostItem } from "@/components/Posts/post"
import Head from 'next/head'

import classes from '@/components/Posts/all-posts.module.css'
import { PostGrid } from "@/components/Posts/post-grid"

const posts: PostItem[] | [] = [ {
  id: 'p1',
  title: 'Getting started with NextJS',
  excerpt: 'NextJS is the React framework for production - it makes building fullstack React apps and sites a breeze and ships with built-in SSR.',
  slug: 'getting-started-with-nextjs',
  content: 'NextJS is the React framework for production - it makes building fullstack React apps and sites a breeze and ships with built-in SSR.',
  image: 'nextjs.png',
  date: '2021-05-10'
},
{
  id: 'p2',
  title: 'Getting started with NestJS 2',
  excerpt: 'NestJS 2 is a progressive Node.js framework for building efficient, reliable and scalable server-side applications.',
  slug: 'getting-started-with-nestjs-2',
  content: 'NestJS 2 is a progressive Node.js framework for building efficient, reliable and scalable server-side applications.',
  image: 'nestjs.png',
  date: '2021-05-11'
}, {
  id: 'p3',
  title: 'Getting started with NestJS 3',
  excerpt: 'NestJS 3 is a progressive Node.js framework for building efficient, reliable and scalable server-side applications.',
  slug: 'getting-started-with-nestjs-3',
  content: 'NestJS 3 is a progressive Node.js framework for building efficient, reliable and scalable server-side applications.',
  image: 'nestjs.png',
  date: '2021-05-13'
} ]

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={classes.posts}>
        <h1>All Posts</h1>
        <PostGrid posts={posts} />
      </section>
    </>
  )
}
